# Generated by Django 3.0.4 on 2021-01-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0005_logaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logaction',
            name='log_config_id',
        ),
        migrations.AddField(
            model_name='logaction',
            name='log_comment',
            field=models.CharField(default='no comment', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logaction',
            name='log_config',
            field=models.ForeignKey(default='no comment', on_delete=django.db.models.deletion.CASCADE, to='newsfeed.Configuration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logaction',
            name='log_action_description',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='logaction',
            name='log_instance_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
