# Generated by Django 3.0.4 on 2021-01-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0007_auto_20210112_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logaction',
            name='log_comment',
        ),
    ]
