# Generated by Django 3.0.4 on 2020-12-17 16:14

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('age', models.BooleanField(default=True)),
                ('gender', models.BooleanField(default=True)),
                ('algoA', models.BooleanField(default=True)),
                ('algoB', models.BooleanField(default=True)),
                ('algoC', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('rating', models.FloatField()),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('author', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=500)),
                ('default', models.BooleanField()),
                ('age', models.BooleanField()),
                ('gender', models.BooleanField()),
                ('algoA', models.BooleanField()),
                ('algoB', models.BooleanField()),
                ('algoC', models.BooleanField()),
            ],
            managers=[
                ('all_news', django.db.models.manager.Manager()),
            ],
        ),
    ]
