# Generated by Django 3.0.4 on 2021-01-08 14:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_instance_creation_date', models.DateTimeField(auto_now_add=True)),
                ('log_identification_string', models.CharField(default='not provided', max_length=200)),
            ],
        ),
        migrations.AlterModelManagers(
            name='configuration',
            managers=[
                ('all_config', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='configuration',
            name='approved',
            field=models.IntegerField(),
        ),
    ]
