# Generated by Django 3.0.4 on 2021-01-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_auto_20210108_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='unapproved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='approved',
            field=models.IntegerField(default=0),
        ),
    ]
