# Generated by Django 3.0.4 on 2020-12-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_auto_20201214_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rating',
            field=models.FloatField(),
        ),
    ]
