# Generated by Django 3.0.4 on 2021-01-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_auto_20210108_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
