# Generated by Django 3.0.4 on 2020-12-15 18:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_auto_20201214_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('age', models.BooleanField(default=True)),
                ('gender', models.BooleanField(default=True)),
                ('algoA', models.BooleanField(default=True)),
                ('algoB', models.BooleanField(default=True)),
                ('algoC', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('all_news', django.db.models.manager.Manager()),
            ],
        ),
    ]
