# Generated by Django 3.0.4 on 2021-01-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0004_configuration_total_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_action_date', models.DateTimeField(auto_now_add=True)),
                ('log_instance_id', models.BigIntegerField()),
                ('log_action_description', models.CharField(max_length=2000)),
                ('log_config_id', models.BigIntegerField()),
            ],
        ),
    ]
