# Generated by Django 3.0.4 on 2021-01-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0010_auto_20210112_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='logaction',
            name='log_comment',
            field=models.CharField(default='no comment', max_length=2000),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
