# Generated by Django 2.2.17 on 2021-02-08 20:59

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0012_auto_20210112_1745'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='loginstance',
            managers=[
                ('all_instance', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='selected_because',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
