# Generated by Django 2.2.17 on 2021-02-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0014_loginstance_current_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='age',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='gender',
        ),
        migrations.AddField(
            model_name='configuration',
            name='algoD',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loginstance',
            name='initial_algo',
            field=models.CharField(default='___D', max_length=4),
        ),
    ]
