# Generated by Django 2.2.17 on 2021-02-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0015_auto_20210216_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='news',
            name='age',
        ),
        migrations.RemoveField(
            model_name='news',
            name='gender',
        ),
        migrations.AddField(
            model_name='news',
            name='algoD',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='news',
            name='algoA',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='news',
            name='algoB',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='news',
            name='algoC',
            field=models.BooleanField(default='False'),
        ),
    ]
