# Generated by Django 2.2.17 on 2021-02-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0017_auto_20210222_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginstance',
            name='comment_algoA',
            field=models.CharField(default='no comment', max_length=2000),
        ),
        migrations.AddField(
            model_name='loginstance',
            name='comment_algoB',
            field=models.CharField(default='no comment', max_length=2000),
        ),
        migrations.AddField(
            model_name='loginstance',
            name='comment_algoC',
            field=models.CharField(default='no comment', max_length=2000),
        ),
        migrations.AddField(
            model_name='loginstance',
            name='comment_algoD',
            field=models.CharField(default='no comment', max_length=2000),
        ),
        migrations.AddField(
            model_name='loginstance',
            name='vote_algoA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginstance',
            name='vote_algoB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginstance',
            name='vote_algoC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginstance',
            name='vote_algoD',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loginstance',
            name='initial_algo',
            field=models.CharField(default='____', max_length=4),
        ),
    ]
