# Generated by Django 2.2.17 on 2021-02-22 14:49

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0018_auto_20210222_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo', models.CharField(default='', max_length=1)),
                ('approved', models.IntegerField(default=0)),
                ('unapproved', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
            ],
            managers=[
                ('all_choices', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='loginstance',
            name='vote_algoA',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='loginstance',
            name='vote_algoB',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='loginstance',
            name='vote_algoC',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='loginstance',
            name='vote_algoD',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
