# Generated by Django 2.2.17 on 2021-02-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0019_auto_20210222_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginstance',
            name='current_algo',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='newsfeed.AlgoChoice'),
            preserve_default='True',
        ),
    ]
