# Generated by Django 2.2.17 on 2021-02-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0020_loginstance_current_algo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='algo',
            field=models.CharField(default='', max_length=1),
        ),
    ]
