# Generated by Django 2.2.17 on 2021-02-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0021_news_algo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginstance',
            name='current_algo',
        ),
    ]
