# Generated by Django 2.2.17 on 2021-02-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0023_loginstance_current_algo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logaction',
            name='log_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.AlgoChoice'),
        ),
    ]
