# Generated by Django 2.2.17 on 2021-02-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0024_auto_20210222_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginstance',
            name='current_algo',
        ),
        migrations.RemoveField(
            model_name='loginstance',
            name='current_config',
        ),
    ]
