# Generated by Django 2.2.17 on 2021-02-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0025_auto_20210223_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='algoA',
        ),
        migrations.RemoveField(
            model_name='news',
            name='algoB',
        ),
        migrations.RemoveField(
            model_name='news',
            name='algoC',
        ),
        migrations.RemoveField(
            model_name='news',
            name='algoD',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='default',
        ),
        migrations.RemoveField(
            model_name='news',
            name='num',
        ),
        migrations.RemoveField(
            model_name='news',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='news',
            name='selected_because',
        ),
    ]
