# Generated by Django 2.2.17 on 2021-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0027_auto_20210223_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
